language: php

php:
- 5.4

mysql:
  database: drupal
  username: root
  encoding: utf8

env:
- UPGRADE=none

matrix:
  fast_finish: true

install:
- export UPDATE TRAVIS_BUILD_DIR
- cp scripts/travis-ci.sh $HOME/
- cd ..
- $HOME/travis-ci.sh system-install

before_script:
- $HOME/travis-ci.sh before-tests

script:
- $HOME/travis-ci.sh run-tests

after_script:
- $HOME/travis-ci.sh after-tests

notifications:
  slack:
    secure: TuH082BihMtKWnUt2N9Bds3Hgc4fw38iOroDbgQYqJc8eLPvVrE2muOsGBRainmvCjGQUYC9GHsEZFoH8SDdaWE6Rns1LQmglH3iCYP2ifPn7qKzfsq3/zj3P311ao6pn7vootYX/qLoYupy2ZC6PPbGLVmppB7keBHrP8tcIg4=
