<?php
/**
 * @file
 * Code for the Slider feature.
 */

include_once('cm_slider.features.inc');

/**
 * Implementation of hook_theme().
 */
function cm_slider_theme($existing) {
  return array(
    'views_view_unformatted__cm_slider' => array(
      'arguments' => array('view' => NULL, 'field' => NULL, 'row' => NULL),
      'template' => 'views-view-unformatted--cm-slider',
      'original hook' => 'views_view_field',
      'path' => drupal_get_path('module', 'cm_slider') . '/theme',
    ),
  );
}
